site_name: Grupo 3 - BRB Mobilidade
repo_url: https://github.com/esmsena/IHC-BRB.Mobilidade-2.2023

theme:
  name: material
  language: pt
  logo: ./docs/assets/brb_logo.png
  favicon: ./docs/assets/brb_logo.png
  features:
    - navigation.footer
    - header.autohide

  plugins:
    - mkdocs-video
  
  favicon: ./assets/twitch_icon.png
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
nav:
    - Início: index.md

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
