site_name: Grupo 3 - BRB Mobilidade
repo_url: https://github.com/esmsena/IHC-BRB.Mobilidade-2.2023

theme:
  name: material
  language: pt
  logo: ./assets/brb_logo.png
  favicon: ./assets/brb_logo.png
  features:
    - navigation.footer
    - header.autohide

  plugins:
    - mkdocs-video
  
  favicon: ./assets/twitch_icon.png
  palette:
    primary: light blue
    accent: blue
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
    - Início: index.md
    - Código de Conduta: CODE_OF_CONDUCT.md
    - Políticas de Contribuição: CONTRIBUTING.md

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true   

